version: '3.9'

# 'nra' stand for nest-react-admin

services:
  backend:
    container_name: nra_backend
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.28
    container_name: nra_db
    restart: always
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: developer
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.mysqldata:/var/lib/mysql
    ports:
      - 4306:3306
    security_opt:
      - seccomp:unconfined
